//! Settings 键按「系统 / 工具」分模块；KV 仍是一张表。

pub mod ocr;
pub mod scripts;
pub mod system;

pub use ocr::{
    engine_setting_key, parse_inspector_placement, DEFAULT_OCR_ACTIVE_ENGINE,
    DEFAULT_OCR_INSPECTOR_PLACEMENT, DEFAULT_OCR_TIMEOUT_MS, OCR_ENGINE_KEY_PREFIX,
    OCR_SETTINGS_VERSION, SETTING_OCR_ACTIVE_ENGINE, SETTING_OCR_INSPECTOR_PLACEMENT,
    SETTING_OCR_SETTINGS_VERSION, SETTING_OCR_TIMEOUT_MS,
};
pub use scripts::{
    DEFAULT_SCRIPTS_ENV_JSON, DEFAULT_SCRIPTS_ENV_PREFIX, DEFAULT_SCRIPTS_PYTHON_PATH,
    SETTING_SCRIPTS_DEFAULT_WORKSPACE, SETTING_SCRIPTS_ENV_JSON, SETTING_SCRIPTS_ENV_PREFIX,
    SETTING_SCRIPTS_PYTHON_PATH,
};
pub use system::{SETTING_DEBUG_ENABLED, SETTING_UI_THEME};
