/// Re-export generated domain types.
export type {
  AppearanceDto,
  ColorScheme,
  OcrEngineFieldInfo,
  OcrEngineInfo,
  OcrFieldKind,
  OcrRect,
  OcrResult,
  OcrSettingsBundle,
  OcrSettingsSave,
  OcrWord,
  ScriptArgsTemplate,
  ScriptCreate,
  ScriptDto,
  ScriptParamDef,
  ScriptParamPassAs,
  ScriptParamType,
  ScriptPathMode,
  ScriptRunRequest,
  ScriptRunResult,
  ScriptSummary,
  ScriptUpdate,
  ScriptsSettingsBundle,
  ScriptsSettingsSave,
  ScriptVenvSummary,
  UiTheme,
} from "./generated";
